### ISSUE TITLE
Plans & progress

### ISSUE THREAD

**Issue by AndyD328** [dakkusingh/google_mybusiness_api#1]
Hi, I just came across this on d.o - figuring I might as well search one more time before making a custom Reviews embed/import and there it was, 1 week old!

Before jumping in and making config forms etc - or backing away and going custom - I thought I'd check if you had any progress that hasn't been pushed here yet and if you had a roadmap/plan for features?

Thanks.

**Comment by dakkusingh** [comment]
@AndyD328 thanks for reaching out.
I am currently working on the module and should have a fleshed out version pushed here and on Drupal in a couple of days.

Will add a plan & roadmap to Drupal project page.

In general this module should provide a tight API coupling between Drupal and GMB APIs..

**Comment by AndyD328** [comment]
Thanks @dakkusingh . I'll sit tight for a week, thanks for your work on this :-)

**Comment by dakkusingh** [comment]
@AndyD328 - Andy, you might want to give the Drupal module a try :)
